version: "3.9"
services:
  db:
    container_name: jav_db_sr
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=oramack25
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javanow_sR_db
    ports:
      - "5432:5432"
    volumes:
      - javanow_pgdata:/var/lib/postgresql/data

volumes:
  javanow_pgdata:
    name: javanow_sR_pgdata
